# Site Settings
title: Twilight Vault Heist Player hand out
description: player hand out for a dnd one shot
theme: jekyll-theme-merlot

# Formatting
show_downloads: false
google_analytics: # Add your ID here if you have one (e.g., UA-XXXXXXXXX-X)

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
